name: Trigger auto deployment for api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/api-AutoDeployTrigger-767a2be7-b66f-4b69-9253-3a999ee06f63.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.API_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.API_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.API_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          # _dockerfilePathKey_: _dockerfilePath_
          dockerfilePath: Dockerfile
          registryUrl: complexus.azurecr.io
          registryUsername: ${{ secrets.API_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.API_REGISTRY_PASSWORD }}
          containerAppName: api
          resourceGroup: production-rg
          imageToBuild: complexus.azurecr.io/api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_

  build-and-deploy-worker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.API_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.API_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.API_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          # _dockerfilePathKey_: _dockerfilePath_
          dockerfilePath: Dockerfile.worker
          registryUrl: complexus.azurecr.io
          registryUsername: ${{ secrets.API_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.API_REGISTRY_PASSWORD }}
          containerAppName: api-worker
          resourceGroup: production-rg
          imageToBuild: complexus.azurecr.io/api-worker:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_
